language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="6a3d60ce-e955-4664-95f6-88ca742773d5"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -Nefedova.Katia@yandex.ru
    on_success: never # default: change
    on_failure: never # default: always